/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerOffersRouteImport } from './routes/manager.offers'
import { Route as ManagerEmployeesRouteImport } from './routes/manager.employees'
import { Route as ManagerAttendanceRouteImport } from './routes/manager.attendance'
import { Route as ManagerActivitiesRouteImport } from './routes/manager.activities'
import { Route as EmployeeProjectsRouteImport } from './routes/employee.projects'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeOffersRouteImport } from './routes/employee.offers'
import { Route as EmployeeLeadsRouteImport } from './routes/employee.leads'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as EmployeeActivitiesRouteImport } from './routes/employee.activities'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as EmployeeLeadsLeadIdRouteImport } from './routes/employee.leads.$leadId'
import { Route as EmployeeActivitiesActivityIdRouteImport } from './routes/employee.activities.$activityId'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminLeadsLeadIdRouteImport } from './routes/admin.leads.$leadId'
import { Route as AdminEmployeesEmployeeIdRouteImport } from './routes/admin.employees.$employeeId'
import { Route as AdminActivitiesActivityIdRouteImport } from './routes/admin.activities.$activityId'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOffersRoute = ManagerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerEmployeesRoute = ManagerEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAttendanceRoute = ManagerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerActivitiesRoute = ManagerActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeProjectsRoute = EmployeeProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOffersRoute = EmployeeOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeadsRoute = EmployeeLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeActivitiesRoute = EmployeeActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeLeadsLeadIdRoute = EmployeeLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => EmployeeLeadsRoute,
} as any)
const EmployeeActivitiesActivityIdRoute =
  EmployeeActivitiesActivityIdRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => EmployeeActivitiesRoute,
  } as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminLeadsLeadIdRoute = AdminLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminEmployeesEmployeeIdRoute =
  AdminEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AdminEmployeesRoute,
  } as any)
const AdminActivitiesActivityIdRoute =
  AdminActivitiesActivityIdRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => AdminActivitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/offers': typeof AdminOffersRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/activities': typeof EmployeeActivitiesRouteWithChildren
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/leads': typeof EmployeeLeadsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/manager/activities': typeof ManagerActivitiesRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/employees': typeof ManagerEmployeesRoute
  '/manager/offers': typeof ManagerOffersRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/employee/activities/$activityId': typeof EmployeeActivitiesActivityIdRoute
  '/employee/leads/$leadId': typeof EmployeeLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activities': typeof AdminActivitiesRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/offers': typeof AdminOffersRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/activities': typeof EmployeeActivitiesRouteWithChildren
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/leads': typeof EmployeeLeadsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/manager/activities': typeof ManagerActivitiesRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/employees': typeof ManagerEmployeesRoute
  '/manager/offers': typeof ManagerOffersRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/employee/activities/$activityId': typeof EmployeeActivitiesActivityIdRoute
  '/employee/leads/$leadId': typeof EmployeeLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/offers': typeof AdminOffersRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/activities': typeof EmployeeActivitiesRouteWithChildren
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/leads': typeof EmployeeLeadsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/manager/activities': typeof ManagerActivitiesRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/employees': typeof ManagerEmployeesRoute
  '/manager/offers': typeof ManagerOffersRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/employee/activities/$activityId': typeof EmployeeActivitiesActivityIdRoute
  '/employee/leads/$leadId': typeof EmployeeLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/settings'
    | '/employee/activities'
    | '/employee/attendance'
    | '/employee/leads'
    | '/employee/offers'
    | '/employee/profile'
    | '/employee/projects'
    | '/manager/activities'
    | '/manager/attendance'
    | '/manager/employees'
    | '/manager/offers'
    | '/manager/reports'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/admin/activities/$activityId'
    | '/admin/employees/$employeeId'
    | '/admin/leads/$leadId'
    | '/admin/projects/$projectId'
    | '/employee/activities/$activityId'
    | '/employee/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/settings'
    | '/employee/activities'
    | '/employee/attendance'
    | '/employee/leads'
    | '/employee/offers'
    | '/employee/profile'
    | '/employee/projects'
    | '/manager/activities'
    | '/manager/attendance'
    | '/manager/employees'
    | '/manager/offers'
    | '/manager/reports'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/activities/$activityId'
    | '/admin/employees/$employeeId'
    | '/admin/leads/$leadId'
    | '/admin/projects/$projectId'
    | '/employee/activities/$activityId'
    | '/employee/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/settings'
    | '/employee/activities'
    | '/employee/attendance'
    | '/employee/leads'
    | '/employee/offers'
    | '/employee/profile'
    | '/employee/projects'
    | '/manager/activities'
    | '/manager/attendance'
    | '/manager/employees'
    | '/manager/offers'
    | '/manager/reports'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/admin/activities/$activityId'
    | '/admin/employees/$employeeId'
    | '/admin/leads/$leadId'
    | '/admin/projects/$projectId'
    | '/employee/activities/$activityId'
    | '/employee/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/offers': {
      id: '/manager/offers'
      path: '/offers'
      fullPath: '/manager/offers'
      preLoaderRoute: typeof ManagerOffersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/employees': {
      id: '/manager/employees'
      path: '/employees'
      fullPath: '/manager/employees'
      preLoaderRoute: typeof ManagerEmployeesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/attendance': {
      id: '/manager/attendance'
      path: '/attendance'
      fullPath: '/manager/attendance'
      preLoaderRoute: typeof ManagerAttendanceRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/activities': {
      id: '/manager/activities'
      path: '/activities'
      fullPath: '/manager/activities'
      preLoaderRoute: typeof ManagerActivitiesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/projects': {
      id: '/employee/projects'
      path: '/projects'
      fullPath: '/employee/projects'
      preLoaderRoute: typeof EmployeeProjectsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/offers': {
      id: '/employee/offers'
      path: '/offers'
      fullPath: '/employee/offers'
      preLoaderRoute: typeof EmployeeOffersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leads': {
      id: '/employee/leads'
      path: '/leads'
      fullPath: '/employee/leads'
      preLoaderRoute: typeof EmployeeLeadsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/activities': {
      id: '/employee/activities'
      path: '/activities'
      fullPath: '/employee/activities'
      preLoaderRoute: typeof EmployeeActivitiesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/leads/$leadId': {
      id: '/employee/leads/$leadId'
      path: '/$leadId'
      fullPath: '/employee/leads/$leadId'
      preLoaderRoute: typeof EmployeeLeadsLeadIdRouteImport
      parentRoute: typeof EmployeeLeadsRoute
    }
    '/employee/activities/$activityId': {
      id: '/employee/activities/$activityId'
      path: '/$activityId'
      fullPath: '/employee/activities/$activityId'
      preLoaderRoute: typeof EmployeeActivitiesActivityIdRouteImport
      parentRoute: typeof EmployeeActivitiesRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/leads/$leadId': {
      id: '/admin/leads/$leadId'
      path: '/$leadId'
      fullPath: '/admin/leads/$leadId'
      preLoaderRoute: typeof AdminLeadsLeadIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/employees/$employeeId': {
      id: '/admin/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/activities/$activityId': {
      id: '/admin/activities/$activityId'
      path: '/$activityId'
      fullPath: '/admin/activities/$activityId'
      preLoaderRoute: typeof AdminActivitiesActivityIdRouteImport
      parentRoute: typeof AdminActivitiesRoute
    }
  }
}

interface AdminActivitiesRouteChildren {
  AdminActivitiesActivityIdRoute: typeof AdminActivitiesActivityIdRoute
}

const AdminActivitiesRouteChildren: AdminActivitiesRouteChildren = {
  AdminActivitiesActivityIdRoute: AdminActivitiesActivityIdRoute,
}

const AdminActivitiesRouteWithChildren = AdminActivitiesRoute._addFileChildren(
  AdminActivitiesRouteChildren,
)

interface AdminEmployeesRouteChildren {
  AdminEmployeesEmployeeIdRoute: typeof AdminEmployeesEmployeeIdRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesEmployeeIdRoute: AdminEmployeesEmployeeIdRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminLeadsRouteChildren {
  AdminLeadsLeadIdRoute: typeof AdminLeadsLeadIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsLeadIdRoute: AdminLeadsLeadIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRouteWithChildren
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRouteWithChildren,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminOffersRoute: AdminOffersRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeActivitiesRouteChildren {
  EmployeeActivitiesActivityIdRoute: typeof EmployeeActivitiesActivityIdRoute
}

const EmployeeActivitiesRouteChildren: EmployeeActivitiesRouteChildren = {
  EmployeeActivitiesActivityIdRoute: EmployeeActivitiesActivityIdRoute,
}

const EmployeeActivitiesRouteWithChildren =
  EmployeeActivitiesRoute._addFileChildren(EmployeeActivitiesRouteChildren)

interface EmployeeLeadsRouteChildren {
  EmployeeLeadsLeadIdRoute: typeof EmployeeLeadsLeadIdRoute
}

const EmployeeLeadsRouteChildren: EmployeeLeadsRouteChildren = {
  EmployeeLeadsLeadIdRoute: EmployeeLeadsLeadIdRoute,
}

const EmployeeLeadsRouteWithChildren = EmployeeLeadsRoute._addFileChildren(
  EmployeeLeadsRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeActivitiesRoute: typeof EmployeeActivitiesRouteWithChildren
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeLeadsRoute: typeof EmployeeLeadsRouteWithChildren
  EmployeeOffersRoute: typeof EmployeeOffersRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeProjectsRoute: typeof EmployeeProjectsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeActivitiesRoute: EmployeeActivitiesRouteWithChildren,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeLeadsRoute: EmployeeLeadsRouteWithChildren,
  EmployeeOffersRoute: EmployeeOffersRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeProjectsRoute: EmployeeProjectsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface ManagerRouteChildren {
  ManagerActivitiesRoute: typeof ManagerActivitiesRoute
  ManagerAttendanceRoute: typeof ManagerAttendanceRoute
  ManagerEmployeesRoute: typeof ManagerEmployeesRoute
  ManagerOffersRoute: typeof ManagerOffersRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerActivitiesRoute: ManagerActivitiesRoute,
  ManagerAttendanceRoute: ManagerAttendanceRoute,
  ManagerEmployeesRoute: ManagerEmployeesRoute,
  ManagerOffersRoute: ManagerOffersRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
